### ISSUE TITLE
Create routes

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [Team-Zlogs/Alumnubhav-Server#2]
1. user
a. new user
b. user login with auth
c. update user info
2. admin
a. new admin
b. admin login with auth
c. update admin information 
3. blog
a. post new blog
b. delete blog
c. edit blog(differed)
4. Resources
a. create resource
b. update resource
c. delete resource
5. Query
a. get all user
b. get user by id
c. get user by query
d. get all blogs
e. get blog by id
f. get blog by query
g. get all resources
h. get resource by id
i. get resource by query

**Comment by IzacVrushabh** [comment]
Close #9
